name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@balt-opi'

      - name: Install dependencies
        run: npm

      #build webcomponents into a package
      - name: Bundle web components
        run: |
          sudo apt install mmv

          # change file extention to story files so `elena build` ignores them
          mmv -r './src/components/*/*/*.stories.*' '#1.stories.xd'
          npx elena build
          # restore to original file extention
          mmv -r './src/components/*/*/*.stories.*' '#1.stories.js'

      - name: Publish package
        run: npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
